services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "45679:45679" # zpages extension
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  service_a:
    build:
      context: ./serviceA
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - otel-collector

  service_b:
    build:
      context: ./serviceB
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
      - otel-collector